---
# tasks file for base

- name: Install base packages
  apt: name={{ item }} update_cache=yes
  sudo: true
  with_items:
     - git
     - mysql-client
     - fail2ban

- name: Setup fail2ban configuration
  template: src=etc-fail2ban-jail-conf dest=/etc/fail2ban/jail.conf
